spec:
  ingressClassName: traefik
  tls:
    - hosts: ["murierromain.com","www.murierromain.com"]
      secretName: porty-prod-tls
  rules:
    - host: murierromain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: porty-front
                port:
                  number: 80
    - host: www.murierromain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: porty-front
                port:
                  number: 80