spec:
  ingressClassName: traefik
  tls:
    - hosts: ["test.murierromain.com"]
      secretName: porty-staging-tls
  rules:
    - host: test.murierromain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: porty-front
                port:
                  number: 80