spec:
  ingressClassName: traefik
  rules:
    - host: test.murierromain.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: porty
                port:
                  number: 80