apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: porty-prod-ingress
  namespace: prod
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts: ["murierromain.com", "www.murierromain.com"]
      secretName: porty-prod-tls
  rules:
    - host: murierromain.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ${APP_NAME}
                port: { number: 80 }
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${FRONT_APP_NAME}
                port: { number: 80 }
    - host: www.murierromain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${FRONT_APP_NAME}
                port: { number: 80 }
