apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: porty-prod-front
  namespace: prod
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts: ["romainmurier.com","www.romainmurier.com"]
      secretName: porty-prod-tls
  rules:
    - host: romainmurier.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: porty-front
                port:
                  number: 80
    - host: www.romainmurier.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: porty-front
                port:
                  number: 80
