apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: porty-staging-ingress
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: staging-noindex@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts: ["test.murierromain.com"]
      secretName: porty-staging-tls
  rules:
    - host: test.murierromain.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ${APP_NAME}
                port: { number: 80 }
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${FRONT_APP_NAME}
                port: { number: 80 }
