apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: porty-staging-front-http
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: test.romainmurier.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: porty-front
                port:
                  number: 80
