apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: porty-staging-ingress
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod   # ← aligne avec le ClusterIssuer existant
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure  # ← HTTP + HTTPS
    traefik.ingress.kubernetes.io/router.middlewares: staging-noindex@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts: ["test.murierromain.com"]
      secretName: porty-staging-tls
  rules:
    - host: test.murierromain.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: porty
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: porty-front
                port:
                  number: 80
