apiVersion: v1
kind: Service
metadata:
  name: mssql
  labels: { app: mssql }
spec:
  type: ClusterIP
  selector: { app: mssql }
  ports:
    - name: tds
      port: 1433
      targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-public
  labels: { app: mssql }
spec:
  type: LoadBalancer
  selector: { app: mssql }
  ports:
    - name: tds-public
      port: ${EXTERNAL_SQL_PORT}   # 1434 en staging, 1435 en prod
      targetPort: 1433
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
  labels: { app: mssql }
spec:
  serviceName: mssql
  replicas: 1
  selector:
    matchLabels: { app: mssql }
  template:
    metadata:
      labels: { app: mssql }
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports: [{ containerPort: 1433 }]
          env:
            - { name: ACCEPT_EULA, value: "Y" }
            - { name: MSSQL_PID, value: "Developer" }
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef: { name: mssql-secret, key: MSSQL_SA_PASSWORD }
          volumeMounts:
            - { name: data, mountPath: /var/opt/mssql }
  volumeClaimTemplates:
    - metadata: { name: data }
      spec:
        accessModes: ["ReadWriteOnce"]
        resources: { requests: { storage: 10Gi } }
